### ISSUE TITLE
params mistype

### ISSUE THREAD

**Issue by jdrzj** [emilianozublena/sheetsu-php#2]
Hi Emiliano 👋 
I'm looking into the code, and I think I found a little bug 🐛  in [sheetsu-php/src/Connection.php:72](https://github.com/emilianozublena/sheetsu-php/blob/1ee3bc177fa330a36b2dae06c80856a36a6146af/src/Connection.php#L72)
The offset can be used if the limit is zero or undefined.

**Comment by emilianozublena** [comment]
Damn right! thanks for pointing that one, if you do a pull-request would be awesome ;) if not, ill be changing it ASAP, til 7th im in a delivery code rush hehe.. cheers!

**Comment by jdrzj** [comment]
Actually I have changes, I will create PR in a minute.

**Comment by emilianozublena** [comment]
Cool, feel free to send anything you see fit... i havent had time to keep polishing this library

**Comment by jdrzj** [comment]
[PR#3](https://github.com/emilianozublena/sheetsu-php/pull/3)

**Comment by emilianozublena** [comment]
merged ;) thanks!

**Comment by jdrzj** [comment]
Sure, it needs some improvements. If it will happen we would like to add this lib to [our docs](docs.sheetsu.com) fully described, so people could use it 👨💻🎉

**Comment by jdrzj** [comment]
Ok, thanks!

**Comment by jdrzj** [comment]
0.0.2? 🙃

**Comment by emilianozublena** [comment]
i think the library is already in your docs, but not fully described...
If there are improvements that you've seen, let me know, so ill know where to start ;)...

My original idea was to complete the Collection+Model abstraction so it leverages the api calls made, but seeing it now... maybe i prefer to hear what you guys have to say and see what comes from it ;)

YEAH! 0.0.2 :D

**Comment by jdrzj** [comment]
Ok, it would be great if ppl could define which `sheet` they are reading or writing to and `ignore_case` when searching.
We care as well about tests, it would be cool to see it here 😃 Our goal is to people could use all sheetsu features with this lib.😍 Let's stay in touch 👊 
0.0.2 🎉 👨‍💻 🎉

**Comment by emilianozublena** [comment]
great ;) the first 2 feats are no brainers, the test's part is whats going to take most of my time ;)

Ill start working in these days and as soon as i have something stable ill go for 0.0.2 ;)

cheers!

**Comment by emilianozublena** [comment]
Andrew! i didnt find any other way to contact you, ive been working on test cases (ive got it to 87% of coverage) and looking to the features you've asked.. i have a few questions..
Every sheet is represented as a "data storage" am i right? if thats so, when you instantiate the sheetsu's lib main object you're defining to which sheet they are writing, reading, etc on...
ie:
`
$sheetsu = new Sheetsu([
     'sheetId' => 'mySheetId'
]);
$sheetsu->read();
`
would trigger this:
`
GET https://sheetsu.com/apis/v1.0/mySheetId/
`

**Comment by emilianozublena** [comment]
Oh sorry, maybe you mean a way of selecting to which sheet do the library write and/or read's?

Maybe some concatenating magic like
`$sheetsu->sheet('mySheetId')->read()`
would be nice...

ill rest and wait for any comments before taking any approach ;)

**Comment by jdrzj** [comment]
Hello Emiliano,
we can discuss such thing on [community.sheetsu.com](http://community.sheetsu.com).

Think sheet as the database, and worksheet as the table. If you initialize sheetsu lib client it should be like:
```
$sheetsu = new Sheetsu([ 'sheetId' => 'mySheetId' ]);
```
and reading with no parameters:
```
$sheetsu->read();
```
`GET https://sheetsu.com/apis/v1.0/mySheetId`

But when you want to read sheet named _foo_ it should be:
```
$sheetsu->read('foo');
```
`GET https://sheetsu.com/apis/v1.0/mySheetId/sheets/foo`

You can reach me as well with my mail: andrew@sheetsu.com :) 👋

**Comment by emilianozublena** [comment]
geez now i see, sorry, seems i've missed this feat when initially set the reqs for this library... we'll keep the conversation elsewhere then
cheers!

**Comment by emilianozublena** [comment]
hi andrew, ive already made all of the changes and are commited as well, if you have the time, please check it out and let me know if there's anything odd ;)

Cheers
