### ISSUE TITLE
Create single element from array does not work

### ISSUE THREAD

**Issue by mikgry** [emilianozublena/sheetsu-php#6]
Hey,
At docs I can see that I can create single row with one-dimension array:
```
# Adds single row from array
$sheetsu->create(['name' => 'John']);
```
But the above code does not work. I see that the request sends:
`"{"rows":{"name":"John"}}"`
And it is not correct. **Rows** should be wrapped in an array:
`"{"rows":[{"name":"John"}}]"`
Or for the single row, the **rows** key should be omitted:
`"{"name":"John"}"`

**Comment by emilianozublena** [comment]
Ill need to test this, it seems odd since all of the test pass fine and also i can see in my test sheets the rows are created ok. Ill check it and get back to you!

**Comment by emilianozublena** [comment]
Although in Sheetsu's docs calls are defined this way, im getting an error from the API itself when trying to send rows in that way.

Please, check tests under /tests, the SheetsuTest unit validates the creation process in testCreateSuccessfullyCreatesDataInApi method and data is correctly created.

**Comment by emilianozublena** [comment]
Done,  now the Sheetsu object checks if the given $insertData is ALSO a multidimensional array, if its not, it will enclose the given $insertData parameter in a array, if it is, it will prepare the json string as before
```
    private function _getParamsFromDataByClassInstance($insertData)
    {
        if ($this->_isValidCollectionInterface($insertData)) {
            return '{"rows":' . $insertData->_prepareCollectionToJson() . '}';
        } elseif ($this->_isValidModelInterface($insertData)) {
            return json_encode($insertData->_prepareModelAsArray());
        } elseif ($this->_isMultidimensionalArray($insertData)) {
            return json_encode(['rows' => $insertData]);
        } else {
            return json_encode(['rows' => [$insertData]]);
        }
    }
```

**Comment by mikgry** [comment]
thanks!
